NetC.JuniorDeveloperExam.Web/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NetC.JuniorDeveloperExam.Web.Models
{
    using Newtonsoft.Json;
    public class BlogPost
    {
        public BlogPost()
        {
        }

        public BlogPost(int v1, string v2, string v3, string v4, string v5, Comment comment)
        {
        }

        [Key]
        public int id { get; set; }
        [DisplayFormat(DataFormatString = "{0: MM/dd/yyyy}")]
        public DateTime date { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string htmlContent{ get; set; }
      public IList<Comment> comments { get; set; }
       

    }
}

NetC.JuniorDeveloperExam.Web/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NetC.JuniorDeveloperExam.Web.Models
{
    public class Comment
    {
        //[Key]
        //public Guid  id { get; set; }
        [Required(ErrorMessage = "Name is required.")]
        public string name { get; set; }
        [DisplayFormat(DataFormatString = "{0: MM/dd/yyyy}")]
        public DateTime date { get; set; }
        [Required(ErrorMessage = "Email  is required.")]
        public string emailAddress { get; set; }
        [Required(ErrorMessage = "Message is required.")]
        public string message { get; set; }
    }
}

NetC.JuniorDeveloperExam.Web/Models/Rootobject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace NetC.JuniorDeveloperExam.Web.Models
{
    public class Rootobject
    {
        [JsonProperty(PropertyName = "blogPosts")]
        public List<BlogPost> blogPosts { get; set; }
    }
}

NetC.JuniorDeveloperExam.Web/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NetC.JuniorDeveloperExam.Web.Models;
using Newtonsoft.Json;

namespace NetC.JuniorDeveloperExam.Web.Controllers
{
    public class BlogPostController :Controller
    {
        [HttpGet]
        public ActionResult Index( int id)
  
        {
           
            string filePath = Server.MapPath("~/App_Data/Blog-Posts.json");
            using (StreamReader r =
                new StreamReader(
                    filePath)
            )
            {
                string json = r.ReadToEnd();

                Rootobject Blogs = JsonConvert.DeserializeObject<Rootobject>(json);
                if(Blogs != null)
                {
                    List<BlogPost> newBlogPosts = (List<BlogPost>)Blogs.blogPosts.Where(b => b.id == id).ToList();


                    return View(newBlogPosts);
                }
                else
                {
                    TempData["message"] = "No Data in Json file to display as blog posts !";
                    return View();
                }

             
            }
        }

        [Route("/BlogPosts/CreateComment/{id}")]
        [HttpPost]
        public ActionResult CreateComment( string Name , string EmailAddress, string Message , int id)
        {

           
           
            try
            {
                  string filePath = Server.MapPath("~/App_Data/Blog-Posts.json");
               

                Comment comment = new Comment();
                //comment.id = Guid.NewGuid();
                comment.name = Name;
                comment.emailAddress = EmailAddress;
                comment.message = Message;
                comment.date = DateTime.Now;

                //
                string json = string.Empty;
                using (StreamReader r = new StreamReader(filePath))
                {
                    json = r.ReadToEnd();
                }
                Rootobject list = JsonConvert.DeserializeObject<Rootobject>(json);

             

                try
                {
                    var newBlogPostComments = list.blogPosts.Where(b => b.id == id).FirstOrDefault().comments;
                    if(newBlogPostComments != null)
                    {
                        newBlogPostComments.Add(comment);
                    }
                    else
                    {
                        List<Comment> newList = new List<Comment>();

                        newList.Add(comment);
                        var newBlogPostCatched = list.blogPosts.Where(b => b.id == id).FirstOrDefault();
                        newBlogPostCatched.comments = newList;
                    }
                 

                }
             
                 catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }




                var convertedJson = JsonConvert.SerializeObject(list, Formatting.Indented);
                
                using (var writer = new StreamWriter(filePath))
                    {
                        writer.Write(convertedJson);
                    }
              
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            return View(); 

        }
    }
}

NetC.JuniorDeveloperExam.Web/Views/BlogPost/CreateComment.cshtml
@{
    ViewBag.Title = "CreateComment";
}

<h2> Added Successfuly </h2>

NetC.JuniorDeveloperExam.Web/Views/BlogPost/Index.cshtml
@model IEnumerable<NetC.JuniorDeveloperExam.Web.Models.BlogPost>
@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" type="text/css" href="/Assets/Styles/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="/Assets/Styles/custom.css" />


@if (Model == null)
{
    var message = TempData["message"];
    <p style="color:red">@message</p>
}
else
{
    foreach (var item in Model)
    {




        <div class="container">
            <div class="row">
                <input type="hidden" value="@item.id" name="id" id="id" />
                <!-- Blog post content -->
                <div class="col-lg-12">

                    <!-- Title  property 3 in json object -->
                    <h1 class="mt-4">@item.title</h1>

                    <hr>

                    <!-- Date/Time  property 2 in json object -->
                    <p> Posted on @item.date</p>

                    <hr>

                    <!-- Preview Image property 4 in json object -->
                    <img class="img-fluid rounded" src=@item.image>
                    <!-- Post Content property 5 in json object  -->
                    <hr>

                    @Html.Raw(item.htmlContent.Replace("<p>", " "))
                    <hr>

                    <!-- Blog post comment form  -->
                    <div class="card my-4">
                        <h5 class="card-header">Leave a Comment:</h5>
                        <div class="card-body">
                           
                            @using (Html.BeginForm("CreateComment", "BlogPost", new { Id = item.id }, FormMethod.Post))
                            {
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="Name">Name</label>

                                        <input type="text" class="form-control" name="Name" id="Name" placeholder="Name" required>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="EmailAddress">Email Address</label>
                                        <input type="email" class="form-control" name="EmailAddress" id="EmailAddress" placeholder="Email Address" required>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="Message">Message</label>
                                    <textarea id="Message" class="form-control" rows="3" name="Message" required></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            }
                           
                        </div>
                    </div>

                    <!-- Blog post comments  property 2 in json object -->

                    @if (@item.comments != null)
                    {
                        foreach (var comment in @item.comments)
                        {
                            <div class="media mb-4">
                                @if (@comment.name == "Steven Barker")
                                {
                                    <img class="d-flex mr-3 rounded-circle user-avatar" src="https://eu.ui-avatars.com/api/?name=Steven+Barker" alt="Steven Barker">
                                }
                                else if (@comment.name == "Chetan Mistry")
                                {
                                    <img class="d-flex mr-3 rounded-circle user-avatar" src="https://eu.ui-avatars.com/api/?name=Chetan+Mistry" alt="Chetan Mistry">
                                }
                                else if (@comment.name == "Chris Grey")
                                {
                                    <img class="d-flex mr-3 rounded-circle user-avatar" src="https://eu.ui-avatars.com/api/?name=Chris+Grey" alt="Chris Grey">
                                }
                                else
                                {

                                }

                                <div class="media-body">
                                    <h5 class="mt-0">@comment.name<small><em>@comment.date</em></small></h5>
                                    @comment.message
                                </div>
                            </div>
                        }
                    }
                    <div id="puzzle1-result"></div>


                </div>

            </div>
        </div>
    }
}

<script>
  
</script>



<script src="/Assets/Scripts/jquery-3.3.1.min.js"></script>
<script src="/Assets/Scripts/jquery.validate.min.js"></script>
<script src="/Assets/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="/Assets/Scripts/unobtrusive-bootstrap.js"></script>
<script src="/Assets/Scripts/bootstrap.bundle.min.js"></script>

NetC.JuniorDeveloperExam.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
   
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NetConstructBlog", "Index", "BlogPost", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>